### ISSUE TITLE
CT cannot read property disposeCircuitElement of null

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-ac#20]
```
circuit-construction-kit-ac : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589809891236/circuit-construction-kit-ac/circuit-construction-kit-ac_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1589809891236%22%2C%22timestamp%22%3A1589810883841%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'disposeCircuitElement' of null
TypeError: Cannot read property 'disposeCircuitElement' of null
at Object.keydown (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589809891236/circuit-construction-kit-common/js/view/CircuitElementNode.js:64:21)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589809891236/scenery/js/input/Input.js:1829:25)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589809891236/scenery/js/input/Input.js:1861:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589809891236/scenery/js/input/Input.js:1787:10)
at Input.dispatchA11yEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589809891236/scenery/js/input/Input.js:1028:12)
at Input.keydownAction.Action.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589809891236/scenery/js/input/Input.js:682:14)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589809891236/axon/js/Action.js:225:18)
at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589809891236/scenery/js/input/Input.js:729:30)
at KeyboardFuzzer.triggerDOMEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589809891236/scenery/js/accessibility/KeyboardFuzzer.js:224:37)
at KeyboardFuzzer.triggerKeyDownUpEvents (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589809891236/scenery/js/accessibility/KeyboardFuzzer.js:117:12)
id: Bayes Chrome
Snapshot from 5/18/2020, 7:51:31 AM
```

**Comment by samreid** [comment]
This problem has been clear for a while, closing.
