### ISSUE TITLE
CT right-hand-side-value must be a number

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-ac#26]
```
circuit-construction-kit-ac : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618459372043/circuit-construction-kit-ac/circuit-construction-kit-ac_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1618459372043%22%2C%22timestamp%22%3A1618464602377%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: the right-hand-side-value must be a number
Error: Assertion failed: the right-hand-side-value must be a number
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618459372043/assert/js/assert.js:25:13)
at ModifiedNodalAnalysisCircuit.solve (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618459372043/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisCircuit.js:352:17)
at DynamicCircuit.solvePropagate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618459372043/circuit-construction-kit-common/js/model/DynamicCircuit.js:150:36)
at DynamicState.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618459372043/circuit-construction-kit-common/js/model/DynamicCircuit.js:398:41)
at Object.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618459372043/circuit-construction-kit-common/js/model/DynamicCircuit.js:162:30)
at TimestepSubdivisions.errorAcceptable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618459372043/circuit-construction-kit-common/js/model/TimestepSubdivisions.js:83:26)
at TimestepSubdivisions.getTimestep (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618459372043/circuit-construction-kit-common/js/model/TimestepSubdivisions.js:65:20)
at TimestepSubdivisions.stepInTimeWithHistory (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618459372043/circuit-construction-kit-common/js/model/TimestepSubdivisions.js:41:32)
at DynamicCircuit.solveWithSubdivisions (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618459372043/circuit-construction-kit-common/js/model/DynamicCircuit.js:167:36)
at Function.solveModifiedNodalAnalysis (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618459372043/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisAdapter.js:179:40)
id: Bayes Chrome
Snapshot from 4/14/2021, 10:02:52 PM
```

**Comment by samreid** [comment]
A reminder to please create CCK-AC issues in the CCK-common repo, thanks!  I'll transfer this one.
