### ISSUE TITLE
CT: Assertion failed: All descendants must be disposed by the next frame

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/circuit-construction-kit-ac#29]
```
circuit-construction-kit-ac : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/circuit-construction-kit-ac/circuit-construction-kit-ac_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1646306694541%22%2C%22timestamp%22%3A1646310164113%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitAc.labScreen.model.circuit.capacitorGroup.capacitor_1.isClearableProperty
Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitAc.labScreen.model.circuit.capacitorGroup.capacitor_1.isClearableProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/tandem/js/PhetioObject.js:531:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/tandem/js/PhetioObject.js:530:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/axon/js/Timer.js:29:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/axon/js/TinyEmitter.js:82:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/joist/js/Sim.js:792:25)
id: Bayes Chrome
Snapshot from 3/3/2022, 4:24:54 AM

----------------------------------

circuit-construction-kit-ac : phet-io-input-record-and-playback-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/phet-io-wrappers/input-record-and-playback/?sim=circuit-construction-kit-ac&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac%22%2C%22phet-io-input-record-and-playback-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1646306694541%22%2C%22timestamp%22%3A1646309930305%7D
Uncaught Error: Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitAc.labScreen.model.circuit.capacitorGroup.capacitor_0.isClearableProperty
Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitAc.labScreen.model.circuit.capacitorGroup.capacitor_0.isClearableProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/tandem/js/PhetioObject.js:531:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/tandem/js/PhetioObject.js:530:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/axon/js/Timer.js:29:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/axon/js/TinyEmitter.js:82:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/joist/js/Sim.js:792:25)
id: Bayes Chrome
Snapshot from 3/3/2022, 4:24:54 AM

----------------------------------

circuit-construction-kit-ac : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/studio/?sim=circuit-construction-kit-ac&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1646306694541%22%2C%22timestamp%22%3A1646311930193%7D
Uncaught Error: Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitAc.labScreen.model.circuit.inductorGroup.inductor_0.isClearableProperty
Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitAc.labScreen.model.circuit.inductorGroup.inductor_0.isClearableProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/tandem/js/PhetioObject.js:531:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/tandem/js/PhetioObject.js:530:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/axon/js/Timer.js:29:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/axon/js/TinyEmitter.js:82:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646306694541/chipper/dist/js/joist/js/Sim.js:792:25)
id: Bayes Chrome
Snapshot from 3/3/2022, 4:24:54 AM
```

**Comment by KatieWoe** [comment]
```
circuit-construction-kit-ac : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/circuit-construction-kit-ac/circuit-construction-kit-ac_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647595636252%22%2C%22timestamp%22%3A1647597388625%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/assert/js/assert.js:25:13)
at VoltageChartNode.sampleLatestValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/circuit-construction-kit-common/js/view/VoltageChartNode.js:86:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/circuit-construction-kit-common/js/view/CCKCScreenView.js:368:54
at Array.forEach (<anonymous>)
at RLCScreenView.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/circuit-construction-kit-common/js/view/CCKCScreenView.js:368:23)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/joist/js/Sim.js:278:21
at PhetioAction.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/tandem/js/PhetioAction.js:90:17)
at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/joist/js/Sim.js:822:31)
at Sim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/joist/js/Sim.js:811:12)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/joist/js/Sim.js:789:12)
id: Bayes Chrome
Snapshot from 3/18/2022, 3:27:16 AM

----------------------------------

circuit-construction-kit-ac : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/circuit-construction-kit-ac/circuit-construction-kit-ac_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647595636252%22%2C%22timestamp%22%3A1647598583073%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitAc.acVoltageScreen.model.circuit.acVoltageGroup.acVoltage_0.isPhaseEditableProperty
Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitAc.acVoltageScreen.model.circuit.acVoltageGroup.acVoltage_0.isPhaseEditableProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/tandem/js/PhetioObject.js:531:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/tandem/js/PhetioObject.js:530:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/axon/js/Timer.js:28:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/axon/js/TinyEmitter.js:81:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/joist/js/Sim.js:794:25)
id: Bayes Chrome
Snapshot from 3/18/2022, 3:27:16 AM

----------------------------------

circuit-construction-kit-ac : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/studio/?sim=circuit-construction-kit-ac&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647595636252%22%2C%22timestamp%22%3A1647597061199%7D
Uncaught Error: Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitAc.labScreen.model.circuit.acVoltageGroup.acVoltage_0.isPhaseEditableProperty
Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitAc.labScreen.model.circuit.acVoltageGroup.acVoltage_0.isPhaseEditableProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/tandem/js/PhetioObject.js:531:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/tandem/js/PhetioObject.js:530:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/axon/js/Timer.js:28:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/axon/js/TinyEmitter.js:81:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/joist/js/Sim.js:794:25)
id: Bayes Chrome
Snapshot from 3/18/2022, 3:27:16 AM

----------------------------------

circuit-construction-kit-ac : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/studio/?sim=circuit-construction-kit-ac&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647595636252%22%2C%22timestamp%22%3A1647607447845%7D
Uncaught Error: Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitAc.labScreen.model.circuit.acVoltageGroup.acVoltage_0.isPhaseEditableProperty
Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitAc.labScreen.model.circuit.acVoltageGroup.acVoltage_0.isPhaseEditableProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/tandem/js/PhetioObject.js:531:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/tandem/js/PhetioObject.js:530:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/axon/js/Timer.js:28:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/axon/js/TinyEmitter.js:81:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/joist/js/Sim.js:794:25)
id: Bayes Chrome
Snapshot from 3/18/2022, 3:27:16 AM
```

**Comment by samreid** [comment]
This problem hasn't appeared on CT for a while, closing.
