### ISSUE TITLE
CT Assertion Failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-ac#30]
```
circuit-construction-kit-ac : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660558781438/circuit-construction-kit-ac/circuit-construction-kit-ac_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1660558781438%22%2C%22timestamp%22%3A1660565224093%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660558781438/assert/js/assert.js:28:13)
at assert (VoltageChartNode.ts:95:14)
at sampleLatestValue (CCKCScreenView.ts:493:54)
at Array.forEach
at forEach (CCKCScreenView.ts:493:22)
at step (Sim.ts:462:18)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1029:30)
at stepSimulation (Sim.ts:1019:11)
at stepOneFrame (Sim.ts:994:11)
id: Bayes Puppeteer
Snapshot from 8/15/2022, 4:19:41 AM

----------------------------------

circuit-construction-kit-ac : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660558781438/circuit-construction-kit-ac/circuit-construction-kit-ac_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1660558781438%22%2C%22timestamp%22%3A1660563806993%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660558781438/assert/js/assert.js:28:13)
at assert (VoltageChartNode.ts:95:14)
at sampleLatestValue (CCKCScreenView.ts:493:54)
at Array.forEach
at forEach (CCKCScreenView.ts:493:22)
at step (Sim.ts:462:18)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1029:30)
at stepSimulation (Sim.ts:1019:11)
at stepOneFrame (Sim.ts:994:11)
id: Bayes Puppeteer
Snapshot from 8/15/2022, 4:19:41 AM

----------------------------------

circuit-construction-kit-ac : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660558781438/circuit-construction-kit-ac/circuit-construction-kit-ac_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1660558781438%22%2C%22timestamp%22%3A1660569791121%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660558781438/assert/js/assert.js:28:13)
at assert (VoltageChartNode.ts:95:14)
at sampleLatestValue (CCKCScreenView.ts:493:54)
at Array.forEach
at forEach (CCKCScreenView.ts:493:22)
at step (Sim.ts:462:18)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1029:30)
at stepSimulation (Sim.ts:1019:11)
at stepOneFrame (Sim.ts:994:11)
id: Bayes Puppeteer
Snapshot from 8/15/2022, 4:19:41 AM

----------------------------------

circuit-construction-kit-ac : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660558781438/circuit-construction-kit-ac/circuit-construction-kit-ac_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1660558781438%22%2C%22timestamp%22%3A1660564074471%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660558781438/assert/js/assert.js:28:13)
at assert (VoltageChartNode.ts:95:14)
at sampleLatestValue (CCKCScreenView.ts:493:54)
at Array.forEach
at forEach (CCKCScreenView.ts:493:22)
at step (Sim.ts:462:18)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1029:30)
at stepSimulation (Sim.ts:1019:11)
at stepOneFrame (Sim.ts:994:11)
id: Bayes Puppeteer
Snapshot from 8/15/2022, 4:19:41 AM

----------------------------------

circuit-construction-kit-ac : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660558781438/circuit-construction-kit-ac/circuit-construction-kit-ac_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1660558781438%22%2C%22timestamp%22%3A1660565679956%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660558781438/assert/js/assert.js:28:13)
at assert (VoltageChartNode.ts:95:14)
at sampleLatestValue (CCKCScreenView.ts:493:54)
at Array.forEach
at forEach (CCKCScreenView.ts:493:22)
at step (Sim.ts:462:18)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1029:30)
at stepSimulation (Sim.ts:1019:11)
at stepOneFrame (Sim.ts:994:11)
id: Bayes Puppeteer
Snapshot from 8/15/2022, 4:19:41 AM
```

**Comment by samreid** [comment]
This has been fixed, closing.
